config/routes.rb
Rails.application.routes.draw do

  resources :graphics
  resources :periods
  resources :comments
  get 'home/index'
  get "disciplines/new_professor" => 'disciplines#new_professor', :as => :new_professor
  get "disciplines/new_comment" => 'disciplines#new_comment', :as => :new_comment_discipline
  resources :mentions
  resources :disciplines
  resources :teachers
  post '/teachers/new' => 'teachers#create', :as => :create_teacher
  post 'disciplines/create_comment_discipline' => 'disciplines#create_comment_discipline'
  post 'discipline/' => 'disciplines#create_comment_discipline'
  root 'sessions#index'
  resources :users
  resource :confirmation, :only => [:show]
  get    'graphics'   => 'graphics#new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :period
  has_many :mention
  has_many :comment
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  #Colocar aqui autenticação na controller
  #before_action :authenticate_user!
  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_professor

  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_professor
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new_comment
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create_comment_discipline
    @comment = Comment.create(comment_params.merge(:user_id => User.last.id, :discipline_id => :discipline_id))
    @comment.user_id = :user_id
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comentário postado' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:name, :amount_credits, :teacher_id, :period_id)
    end

    def comment_params
      params.require(:comment).permit(:user_id, :discipline_id, :body)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= form_for @discipline, :html => { :class => "form-horizontal col-lg-12" } do |f| %>

  <% if @discipline.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@discipline.errors.count, "error") %> prohibited this discipline from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @discipline.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :amount_credits, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :amount_credits, :class => 'form-control' %>
    </div>
    <%=f.error_span(:amount_credits) %>
  </div>
  <div class="form-group">
    <%= f.label :teacher_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :teacher_id, Teacher.all, :id, :name, {include_blank: true}, {class: 'form-control'} %>
    </div>
    <%=f.error_span(:teacher_id) %>
  </div>
  <div class="form-group">
    <%= f.label :period_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :period_id, Period.all, :id, :name, {include_blank: true}, {:class => 'form-control'} %>
    </div>
    <%=f.error_span(:period_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                disciplines_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/disciplines/_new_comment.html.erb
<form accept-charset="UTF-8" action="/discipline" class="new_comment" id="new_comment" method="post">
  <div class="modal-dialog" id="myModalLabel">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Novo Comentário</h3>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <input class="form-control" id="comentario" name="comment[body]" type="text_field">
          <input class="form-control" id="modal_value" type="hidden" name="modal" value="true">
        </div>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        <%= button_to "Comentar", {:controller=> "disciplines", :action => "create_comment_discipline"} ,  :method => :post, :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</form>

app/views/disciplines/_new_professor.html.erb
<form accept-charset="UTF-8" action="/teachers" class="new_teacher" id="new_teacher" method="post">
<div class="modal-dialog" id="myModalLabel">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3>Cadastrar Novo Professor</h3>
    </div>
    <div class="modal-body">
      <div class="form-group">
        <input class="form-control" id="teacher_name" name="teacher[name]" type="text_field">
        <input class="form-control" id="modal_value" type="hidden" name="modal" value="true">
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Cancelar</button>
      <%= button_to "Cadastrar Professor", create_teacher_path , :method => :post, :class => "btn btn-primary" %>
    </div>
  </div>
</div>
</form>

app/views/disciplines/edit.html.erb
<%- model_class = Discipline -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/disciplines/index.html.erb
<%- model_class = Discipline -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Créditos</th>
      <% if current_user.type_user == 'admin'%>
        <th>Ações</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= link_to discipline.name, discipline_path(discipline)%></td>
        <td><%= discipline.amount_credits %></td>
        <% if current_user.type_user == 'admin'%>
          <td class="buttons">
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_discipline_path(discipline), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        discipline_path(discipline),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.type_user == 'admin'%>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_discipline_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/disciplines/new.html.erb
<%- model_class = Discipline -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'Nova %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/disciplines/new_comment.js.erb
$("#modal-comment").html("<%= escape_javascript(render 'disciplines/new_comment') %>");

app/views/disciplines/new_professor.js.erb
/**
 * Created by pedro on 01/10/16.
 */

$("#modal-professor").html("<%= escape_javascript(render 'disciplines/new_professor') %>");

app/views/disciplines/show.html.erb
<%- model_class = Discipline -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @discipline.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount_credits) %>:</strong></dt>
  <dd><%= @discipline.amount_credits %></dd>
</dl>
<div class="buttons">
<% if current_user.type_user == 'admin'%>
  <%= link_to t('.back', :default => t("helpers.links.back")),
                disciplines_path, :class => 'btn btn-default'  %>
  <% if current_user.type_user == 'admin'%>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_discipline_path(@discipline), :class => 'btn btn-primary' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  discipline_path(@discipline),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
  <% end %>
<% end %>
<br/><br/>
  <%= link_to 'Novo comentario', new_comment_discipline_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-comment', :class => 'btn btn-info', :discipline_id => @discipline.id} %>
</div>
<% comments = Comment.where("discipline_id = " + @discipline.id.to_s)%>
<% comments.each do |comment| %>
    <%= comment.body %>
<% end %>
<div id="modal-comment" class="modal fade" role="dialog" tabindex="-1" aria-labelledby="myModalLabel" aria-hidden="true"></div>