config/routes.rb
Rails.application.routes.draw do

  resources :graphics
  resources :periods
  resources :comments
  get 'home/index'
  get "disciplines/new_professor" => 'disciplines#new_professor', :as => :new_professor
  get "disciplines/new_comment" => 'disciplines#new_comment', :as => :new_comment_discipline
  resources :mentions
  resources :disciplines
  resources :teachers
  post '/teachers/new' => 'teachers#create', :as => :create_teacher
  post 'disciplines/create_comment_discipline' => 'disciplines#create_comment_discipline'
  post 'discipline/' => 'disciplines#create_comment_discipline'
  root 'sessions#index'
  resources :users
  resource :confirmation, :only => [:show]
  get    'graphics'   => 'graphics#new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.type_user == 'admin' && !current_user.nil?
      can :manage, :all
    elsif user.type_user == 'visitor' && !current_user.nil?
      cannot :manage, Period
      cannot :manage, Discipline
      cannot :manage, Teacher
      cannot :manage, User
      cannot :manage, Session
      can :manage, Mention
      asdas
    else
      cannot :manage, Period
      cannot :manage, Discipline
      cannot :manage, Teacher
      cannot :manage, User
      cannot :manage, Session
      cannot :manage, Mention
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discipline
end

app/models/common_average.rb
class CommonAverage < ActiveRecord::Base
  include MentionCalculate
  attr_accessor :scorep1, :scorep2, :scopep3

  def calcular
    (scorep1+scorep2+scopep3)/3
  end

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :period
  has_many :mention
  has_many :comment
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :discipline
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :discipline
end

app/models/square_root.rb
class SquareRoot < ActiveRecord::Base
  include MentionCalculate

  def calcular
    Math.sqrt(scorep1*scoret1*scoree1)
  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :discipline
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    # validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_create :generate_token
    before_save { self.email = email.downcase }
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    def generate_token
      self.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
      return if confirmed?

      self.confirmed_at = Time.current
      self.confirmation_token = ''
      save!
    end

    def confirmed?
      confirmed_at.present?
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController
  before_action :set_period, only: [:show, :edit, :update, :destroy]

  # GET /periods
  # GET /periods.json
  def index
    @periods = Period.all
  end

  # GET /periods/1
  # GET /periods/1.json
  def show
  end

  # GET /periods/new
  def new
    @period = Period.new
  end

  # GET /periods/1/edit
  def edit
  end

  # POST /periods
  # POST /periods.json
  def create
    @period = Period.new(period_params)

    respond_to do |format|
      if @period.save
        format.html { redirect_to @period, notice: 'Period was successfully created.' }
        format.json { render :show, status: :created, location: @period }
      else
        format.html { render :new }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /periods/1
  # PATCH/PUT /periods/1.json
  def update
    respond_to do |format|
      if @period.update(period_params)
        format.html { redirect_to @period, notice: 'Period was successfully updated.' }
        format.json { render :show, status: :ok, location: @period }
      else
        format.html { render :edit }
        format.json { render json: @period.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /periods/1
  # DELETE /periods/1.json
  def destroy
    @period.destroy
    respond_to do |format|
      format.html { redirect_to periods_url, notice: 'Period was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_period
      @period = Period.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def period_params
      params.require(:period).permit(:name, :start, :finish)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authorize, except: [:new, :create]
    before_action :correct_user?, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            SignupMailer.confirm_email(@user).deliver
            redirect_to @user, notice: "Usuário foi criado com sucesso!"
        else
            render action: :new
        end
    end

    def index
      @users = User.all
    end

     def show
      @user = User.find(params[:id])
     end

     def update
         @user = User.find(params[:id])
         if @user.update_attributes(user_params)
             flash[:success]= "Usuário atualizado"
             redirect_to @user
         else
             render 'edit'
         end
     end

     def destroy
         @user = User.find(params[:id])
         @user.destroy
         flash[:success] = "Usuário foi deletado"
         redirect_to users_path
     end

     def edit
         @user = User.find(params[:id])
     end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag :div, model.errors[attribute].first,
      :class => 'error_message'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper

  @@sr = 0
  @@ii = 0
  @@mi = 0
  @@mm = 0
  @@ms = 0
  @@ss = 0

  def self.build_mention
    mention = Mention.all
    mention.each do |m|
       if m.value == 'SR'
         @@sr = @@sr + 1
       end
       if m.value == 'II'
         @@ii = @@ii + 1
       end
       if m.value == 'MI'
         @@mi = @@mi + 1
       end
       if m.value == 'MM'
         @@mm = @@mm + 1
       end
       if m.value == 'MS'
         @@ms = @@ms + 1
       end
       if m.value == 'SS'
         @@ss = @@ss + 1
       end
     end
  end

  def self.sr
    @@sr
  end
  def self.ii
    @@ii
  end

  def self.mi
    @@mi
  end
  def self.mm
    @@mm
  end

  def self.ms
    @@ms
  end

  def self.ss
    @@ss
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mentions_helper.rb
module MentionsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
        if current_user.present?
            redirect_to users_path
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/periods/_form.html.erb
<%= form_for @period, :html => { :class => "form-horizontal col-lg-12" } do |f| %>

  <% if @period.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@period.errors.count, "error") %> prohibited this period from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @period.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :start, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :start,
      {:order => [:day, :month, :year], :start_year => 1940},
      {class: 'form-control'} %>
    </div>
    <%=f.error_span(:start) %>
  </div>
  <div class="form-group">
    <%= f.label :finish, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select :finish,
      {:order => [:day, :month, :year], :start_year => 1940},
      {class: 'form-control'} %>
    </div>
    <%=f.error_span(:finish) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                periods_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/periods/edit.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/periods/index.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:start) %></th>
      <th><%= model_class.human_attribute_name(:finish) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @periods.each do |period| %>
      <tr>
        <td><%= link_to period.id, period_path(period) %></td>
        <td><%= period.name %></td>
        <td><%= period.start %></td>
        <td><%= period.finish %></td>
        <td><%=l period.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_period_path(period), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      period_path(period),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_period_path,
            :class => 'btn btn-primary' %>

app/views/periods/new.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/periods/show.html.erb
<%- model_class = Period -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.titleize %></h2>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @period.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start) %>:</strong></dt>
  <dd><%= @period.start %></dd>
  <dt><strong><%= model_class.human_attribute_name(:finish) %>:</strong></dt>
  <dd><%= @period.finish %></dd>
</dl>
<div class="buttons">
<%= link_to t('.back', :default => t("helpers.links.back")),
              periods_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_period_path(@period), :class => 'btn btn-primary' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              period_path(@period),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal col-lg-12" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password) %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.password_field :password_confirmation, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password_confirmation) %>
  </div>
  <div class="form-group">
    <%= f.label :avatar, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :avatar, :class => 'form-control' %>
    </div>
    <%=f.error_span(:password_confirmation) %>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Cadastrar', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("Ações") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.email %></td>
        <td>
          <%= link_to t('.edit', :default => t("Editar")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("Deletar")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Confirmar deleção do usuário?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h2>Meu perfil</h2>
</div>
<span class="user-image"><%= image_tag @user.avatar.url(:thumb), class:'user-image' %></span>
<dl class="dl-horizontal-profile">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>
<div class="buttons">
<%= link_to t('.back', :default => t("Voltar")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("Editar")),
              edit_user_path(@user), :class => 'btn btn-primary' %>
<%= link_to t('.destroy', :default => t("Deletar")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>