config/routes.rb
Rails.application.routes.draw do

  resources :graphics
  resources :periods
  resources :comments
  get 'home/index'
  get "disciplines/new_professor" => 'disciplines#new_professor', :as => :new_professor
  get "disciplines/new_comment" => 'disciplines#new_comment', :as => :new_comment_discipline
  resources :mentions
  resources :disciplines
  resources :teachers
  post '/teachers/new' => 'teachers#create', :as => :create_teacher
  post 'disciplines/create_comment_discipline' => 'disciplines#create_comment_discipline'
  post 'discipline/' => 'disciplines#create_comment_discipline'
  root 'sessions#index'
  resources :users
  resource :confirmation, :only => [:show]
  get    'graphics'   => 'graphics#new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.type_user == 'admin' && !current_user.nil?
      can :manage, :all
    elsif user.type_user == 'visitor' && !current_user.nil?
      cannot :manage, Period
      cannot :manage, Discipline
      cannot :manage, Teacher
      cannot :manage, User
      cannot :manage, Session
      can :manage, Mention
      asdas
    else
      cannot :manage, Period
      cannot :manage, Discipline
      cannot :manage, Teacher
      cannot :manage, User
      cannot :manage, Session
      cannot :manage, Mention
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discipline
end

app/models/common_average.rb
class CommonAverage < ActiveRecord::Base
  include MentionCalculate
  attr_accessor :scorep1, :scorep2, :scopep3

  def calcular
    (scorep1+scorep2+scopep3)/3
  end

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :period
  has_many :mention
  has_many :comment
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :discipline
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :discipline
end

app/models/square_root.rb
class SquareRoot < ActiveRecord::Base
  include MentionCalculate

  def calcular
    Math.sqrt(scorep1*scoret1*scoree1)
  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :discipline
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    # validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_create :generate_token
    before_save { self.email = email.downcase }
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    def generate_token
      self.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
      return if confirmed?

      self.confirmed_at = Time.current
      self.confirmation_token = ''
      save!
    end

    def confirmed?
      confirmed_at.present?
    end

end

app/controllers/graphics_controller.rb
class GraphicsController < ApplicationController
  before_action :set_graphic, only: [:show, :edit, :update, :destroy]

  # GET /graphics
  # GET /graphics.json
  def index
    @graphics = Graphic.all
  end

  # GET /graphics/1
  # GET /graphics/1.json
  def show
  end

  # GET /graphics/new
  def new
    @graphic = Graphic.new
  end

  # GET /graphics/1/edit
  def edit
  end

  # POST /graphics
  # POST /graphics.json
  def create
    @graphic = Graphic.new(graphic_params)

    respond_to do |format|
      if @graphic.save
        format.html { redirect_to @graphic, notice: 'Graphic was successfully created.' }
        format.json { render :show, status: :created, location: @graphic }
      else
        format.html { render :new }
        format.json { render json: @graphic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graphics/1
  # PATCH/PUT /graphics/1.json
  def update
    respond_to do |format|
      if @graphic.update(graphic_params)
        format.html { redirect_to @graphic, notice: 'Graphic was successfully updated.' }
        format.json { render :show, status: :ok, location: @graphic }
      else
        format.html { render :edit }
        format.json { render json: @graphic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphics/1
  # DELETE /graphics/1.json
  def destroy
    @graphic.destroy
    respond_to do |format|
      format.html { redirect_to graphics_url, notice: 'Graphic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graphic
      @graphic = Graphic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graphic_params
      params.fetch(:graphic, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authorize, except: [:new, :create]
    before_action :correct_user?, only: [:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            SignupMailer.confirm_email(@user).deliver
            redirect_to @user, notice: "Usuário foi criado com sucesso!"
        else
            render action: :new
        end
    end

    def index
      @users = User.all
    end

     def show
      @user = User.find(params[:id])
     end

     def update
         @user = User.find(params[:id])
         if @user.update_attributes(user_params)
             flash[:success]= "Usuário atualizado"
             redirect_to @user
         else
             render 'edit'
         end
     end

     def destroy
         @user = User.find(params[:id])
         @user.destroy
         flash[:success] = "Usuário foi deletado"
         redirect_to users_path
     end

     def edit
         @user = User.find(params[:id])
     end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag :div, model.errors[attribute].first,
      :class => 'error_message'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper

  @@sr = 0
  @@ii = 0
  @@mi = 0
  @@mm = 0
  @@ms = 0
  @@ss = 0

  def self.build_mention
    mention = Mention.all
    mention.each do |m|
       if m.value == 'SR'
         @@sr = @@sr + 1
       end
       if m.value == 'II'
         @@ii = @@ii + 1
       end
       if m.value == 'MI'
         @@mi = @@mi + 1
       end
       if m.value == 'MM'
         @@mm = @@mm + 1
       end
       if m.value == 'MS'
         @@ms = @@ms + 1
       end
       if m.value == 'SS'
         @@ss = @@ss + 1
       end
     end
  end

  def self.sr
    @@sr
  end
  def self.ii
    @@ii
  end

  def self.mi
    @@mi
  end
  def self.mm
    @@mm
  end

  def self.ms
    @@ms
  end

  def self.ss
    @@ss
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mentions_helper.rb
module MentionsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
        if current_user.present?
            redirect_to users_path
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/graphics/_form.html.erb
<%= form_for(@graphic) do |f| %>
  <% if @graphic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@graphic.errors.count, "error") %> prohibited this graphic from being saved:</h2>

      <ul>
      <% @graphic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graphics/edit.html.erb
<h1>Editing Graphic</h1>

<%= render 'form' %>

<%= link_to 'Show', @graphic %> |
<%= link_to 'Back', graphics_path %>

app/views/graphics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Graphics</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graphics.each do |graphic| %>
      <tr>
        <td><%= link_to 'Show', graphic %></td>
        <td><%= link_to 'Edit', edit_graphic_path(graphic) %></td>
        <td><%= link_to 'Destroy', graphic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Graphic', new_graphic_path %>

app/views/graphics/new.html.erb
<h1  align="left" >Gráficos</h1>

<!---<div class="form-group">
  <div class="col-lg-5">
    <% discipline = Discipline.all %>
    <select class="form-control" id="filter-discipline" >
      <% discipline.each do |m| %>
        <option value="<%= m.name %>"> <%= m.name %> </option>
      <% end %>
    </select>
  </div>
</div>
<button class="form-group" onclick="getValueSelected()">Ok</button>
<% GraphicsHelper.build_mention %>
<!-- <h4>more informations https://google-developers.appspot.com/chart/interactive/docs/gallery/piechart#fullhtml </h4> -->

<html>
 <head>
   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
     google.charts.load("current", {packages:["corechart"]});
     google.charts.setOnLoadCallback(drawChartPieChart);
     google.charts.setOnLoadCallback(drawChartColumnChart);

     function getValueSelected(){
      alert(document.getElementById("filter-discipline").value);
     }

     function drawChartPieChart() {
       var data = google.visualization.arrayToDataTable([
         ['Task', 'Hours per Day'],
         ['SR',     <%= GraphicsHelper.sr %>],
         ['II',     <%= GraphicsHelper.ii %>],
         ['MI',      <%= GraphicsHelper.mi %>],
         ['MM',  <%= GraphicsHelper.mm %>],
         ['MS', <%= GraphicsHelper.ms %>],
         ['SS',    <%= GraphicsHelper.ss %>]
       ]);

       var options = {
         title: 'Gráfico de pizza',
         pieHole: 0.4,
       };

       var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
       chart.draw(data, options);
     }

     function drawChartColumnChart() {
       var data = google.visualization.arrayToDataTable([
         ["Element", "Density", { role: "style" } ],
         ["SR", <%= GraphicsHelper.sr %>, "#3366cc"],
         ["II", <%= GraphicsHelper.ii %>, "#dc3912"],
         ["MI", <%= GraphicsHelper.mi %>, "#ff9900"],
         ["MM", <%= GraphicsHelper.mm %>, "#109618"],
         ["MS", <%= GraphicsHelper.ms %>, "#990099"],
         ["SS", <%= GraphicsHelper.ss %>, "#0099c6"]
       ]);

       var view = new google.visualization.DataView(data);
       view.setColumns([0, 1,
                        { calc: "stringify",
                          sourceColumn: 1,
                          type: "string",
                          role: "annotation" },
                        2]);

       var options = {
         title: "Gráficos de barras",
         width: 600,
         height: 400,
         bar: {groupWidth: "95%"},
         legend: { position: "none" },
       };
       var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
       chart.draw(view, options);
    }

   </script>
 </head>
 <body>
   <div id="donutchart" style="width: 900px; height: 500px;"></div>
 </body>
  <body>
    <div id="columnchart_values" style="width: 900px; height: 300px;"></div>
  </body>
</html>

app/views/graphics/show.html.erb
<!--<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_graphic_path(@graphic) %> |
<%= link_to 'Back', graphics_path %>-->

<h1  align="left" >Gráficos</h1>

<!---<div class="form-group">
  <div class="col-lg-5">
    <% discipline = Discipline.all %>
    <select class="form-control" id="filter-discipline" >
      <% discipline.each do |m| %>
        <option value="<%= m.name %>"> <%= m.name %> </option>
      <% end %>
    </select>
  </div>
</div>
<button class="form-group" onclick="getValueSelected()">Ok</button>
<% GraphicsHelper.build_mention %>
<!-- <h4>more informations https://google-developers.appspot.com/chart/interactive/docs/gallery/piechart#fullhtml </h4> -->

<html>
 <head>
   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
   <script type="text/javascript">
     google.charts.load("current", {packages:["corechart"]});
     google.charts.setOnLoadCallback(drawChartPieChart);
     google.charts.setOnLoadCallback(drawChartColumnChart);

     function getValueSelected(){
      alert(document.getElementById("filter-discipline").value);
     }

     function drawChartPieChart() {
       var data = google.visualization.arrayToDataTable([
         ['Task', 'Hours per Day'],
         ['SR',     <%= GraphicsHelper.sr %>],
         ['II',     <%= GraphicsHelper.ii %>],
         ['MI',      <%= GraphicsHelper.mi %>],
         ['MM',  <%= GraphicsHelper.mm %>],
         ['MS', <%= GraphicsHelper.ms %>],
         ['SS',    <%= GraphicsHelper.ss %>]
       ]);

       var options = {
         title: 'Gráfico de pizza',
         pieHole: 0.4,
       };

       var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
       chart.draw(data, options);
     }

     function drawChartColumnChart() {
       var data = google.visualization.arrayToDataTable([
         ["Element", "Density", { role: "style" } ],
         ["SR", <%= GraphicsHelper.sr %>, "#3366cc"],
         ["II", <%= GraphicsHelper.ii %>, "#dc3912"],
         ["MI", <%= GraphicsHelper.mi %>, "#ff9900"],
         ["MM", <%= GraphicsHelper.mm %>, "#109618"],
         ["MS", <%= GraphicsHelper.ms %>, "#990099"],
         ["SS", <%= GraphicsHelper.ss %>, "#0099c6"]
       ]);

       var view = new google.visualization.DataView(data);
       view.setColumns([0, 1,
                        { calc: "stringify",
                          sourceColumn: 1,
                          type: "string",
                          role: "annotation" },
                        2]);

       var options = {
         title: "Gráficos de barras",
         width: 600,
         height: 400,
         bar: {groupWidth: "95%"},
         legend: { position: "none" },
       };
       var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
       chart.draw(view, options);
    }

   </script>
 </head>
 <body>
   <div id="donutchart" style="width: 900px; height: 500px;"></div>
 </body>
  <body>
    <div id="columnchart_values" style="width: 900px; height: 300px;"></div>
  </body>
</html>