config/routes.rb
Rails.application.routes.draw do

  resources :graphics
  resources :periods
  resources :comments
  get 'home/index'
  get "disciplines/new_professor" => 'disciplines#new_professor', :as => :new_professor
  get "disciplines/new_comment" => 'disciplines#new_comment', :as => :new_comment_discipline
  resources :mentions
  resources :disciplines
  resources :teachers
  post '/teachers/new' => 'teachers#create', :as => :create_teacher
  post 'disciplines/create_comment_discipline' => 'disciplines#create_comment_discipline'
  post 'discipline/' => 'disciplines#create_comment_discipline'
  root 'sessions#index'
  resources :users
  resource :confirmation, :only => [:show]
  get    'graphics'   => 'graphics#new'
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.type_user == 'admin' && !current_user.nil?
      can :manage, :all
    elsif user.type_user == 'visitor' && !current_user.nil?
      cannot :manage, Period
      cannot :manage, Discipline
      cannot :manage, Teacher
      cannot :manage, User
      cannot :manage, Session
      can :manage, Mention
      asdas
    else
      cannot :manage, Period
      cannot :manage, Discipline
      cannot :manage, Teacher
      cannot :manage, User
      cannot :manage, Session
      cannot :manage, Mention
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :discipline
end

app/models/common_average.rb
class CommonAverage < ActiveRecord::Base
  include MentionCalculate
  attr_accessor :scorep1, :scorep2, :scopep3

  def calcular
    (scorep1+scorep2+scopep3)/3
  end

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :period
  has_many :mention
  has_many :comment
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :discipline
end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :discipline
end

app/models/square_root.rb
class SquareRoot < ActiveRecord::Base
  include MentionCalculate

  def calcular
    Math.sqrt(scorep1*scoret1*scoree1)
  end

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :discipline
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    # validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_create :generate_token
    before_save { self.email = email.downcase }
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

    def generate_token
      self.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
      return if confirmed?

      self.confirmed_at = Time.current
      self.confirmation_token = ''
      save!
    end

    def confirmed?
      confirmed_at.present?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_tag(model, attribute)
    if model.errors.has_key? attribute
      content_tag :div, model.errors[attribute].first,
      :class => 'error_message'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper

  @@sr = 0
  @@ii = 0
  @@mi = 0
  @@mm = 0
  @@ms = 0
  @@ss = 0

  def self.build_mention
    mention = Mention.all
    mention.each do |m|
       if m.value == 'SR'
         @@sr = @@sr + 1
       end
       if m.value == 'II'
         @@ii = @@ii + 1
       end
       if m.value == 'MI'
         @@mi = @@mi + 1
       end
       if m.value == 'MM'
         @@mm = @@mm + 1
       end
       if m.value == 'MS'
         @@ms = @@ms + 1
       end
       if m.value == 'SS'
         @@ss = @@ss + 1
       end
     end
  end

  def self.sr
    @@sr
  end
  def self.ii
    @@ii
  end

  def self.mi
    @@mi
  end
  def self.mm
    @@mm
  end

  def self.ms
    @@ms
  end

  def self.ss
    @@ss
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mentions_helper.rb
module MentionsHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
        if current_user.present?
            redirect_to users_path
        end
    end
    def logged_in?
        !current_user.nil?
    end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse">
    <ul class="nav navbar-nav">
        <% if logged_in? %>
            <li class="link"><%= link_to "Home", home_index_path, class: "navbar-brand"  %></li>
            <% if current_user.type_user == 'admin'%>
              <li class="link"><%= link_to "Users", users_path, class: "navbar-brand"  %></li>
              <li class="link"><%= link_to "Professores", teachers_path, class: "navbar-brand"  %></li>
              <li class="link"><%= link_to "Períodos", periods_path, class: "navbar-brand"  %></li>
            <% end %>
            <li class="link"><%= link_to "Profile", current_user, class: "navbar-brand"  %></li>
            <li class="link"><%= link_to "Disciplinas", disciplines_path, class: "navbar-brand"  %></li>
            <li class="link"><%= link_to "Menções", mentions_path, class: "navbar-brand"  %></li>
            <li class="link"><%= link_to "Gráficos", graphics_path, method: "new", class: "navbar-brand"  %></li>
            <li class="link"><%= link_to "Log out", sign_out_path, method: "delete", class: "navbar-brand"  %></li>
        <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if !logged_in? %>
        <li class="link"><%= link_to "Log in", sign_in_path, class: "navbar-brand"%></li>
      <% else %>
        <li class="welcome-user"><%="Olá, %s" % current_user.name %></li>
        <li class="user-profile-image"><%=image_tag current_user.avatar.url(:thumb),  class:'user-profile-image'%></li>
      <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>SiCAD</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <%= yield %>
</body>
</html>